version: '3'
volumes:
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakdbpswrd
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloakdbpswrd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpswrd
    ports:
      - '9080:8080'
    command:
      - start-dev
    depends_on:
      - postgres